"""
Contains the paths of the delta tables
"""
cards_bronze_table_path = '/home/ubuntu/lakehouse_project/data_tables/bronze_cards_table'
members_bronze_table_path = '/home/ubuntu/lakehouse_project/data_tables/bronze_members_table'
cards_silver_table_path = '/home/ubuntu/lakehouse_project/data_tables/silver_cards_table'
noactive_cards_gold_path = '/home/ubuntu/lakehouse_project/data_tables/gold_noactive_cards_table'
cards_unique_silver_table_path = '/home/ubuntu/lakehouse_project/data_tables/silver_unique_cards_table'
sravanti_cards_gold_path = '/home/ubuntu/lakehouse_project/data_tables/sravanti_cards_gold_table'
akkul_cards_gold_path = '/home/ubuntu/lakehouse_project/data_tables/akkul_cards_gold_table'
avinash_cards_gold_path = '/home/ubuntu/lakehouse_project/data_tables/avinash_cards_gold_table'
archana_cards_gold_path = '/home/ubuntu/lakehouse_project/data_tables/archana_cards_gold_table'
ajitava_cards_gold_path = '/home/ubuntu/lakehouse_project/data_tables/ajitava_cards_gold_table'
drishya_cards_gold_path = '/home/ubuntu/lakehouse_project/data_tables/drishya_cards_gold_table'
indira_cards_gold_path = '/home/ubuntu/lakehouse_project/data_tables/indira_cards_gold_table'
mohan_cards_gold_path = '/home/ubuntu/lakehouse_project/data_tables/mohan_cards_gold_table'
preedhi_cards_gold_path = '/home/ubuntu/lakehouse_project/data_tables/preedhi_cards_gold_table'
raghava_cards_gold_path = '/home/ubuntu/lakehouse_project/data_tables/raghava_cards_gold_table'
raji_cards_gold_path = '/home/ubuntu/lakehouse_project/data_tables/raji_cards_gold_table'
rohan_cards_gold_path = '/home/ubuntu/lakehouse_project/data_tables/rohan_cards_gold_table'
shiva_cards_gold_path = '/home/ubuntu/lakehouse_project/data_tables/shiva_cards_gold_table'
